data(iris)
head(iris)
iris_data=iris[,1:4]
distance_matrix=dist(iris_data,method="euclidean")
print(distance_matrix)
hc_model<-hclust(distance_matrix,method="ward.D2")
print(hc_model)
plot(hc_model,labels=FALSE,hang=-1,main="Hierarchical clustering dendrogram",xlab="observation",ylab="weight")
rect.hclust(hc_model,k=3,border="red")
cluster<-cutree(hc_model,k=3)
cat("cluster assignment:\n")
print(cluster)
cat("\ncluster size:\n")
print(table (cluster))
